version: '3.3'

services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "${APP_PORT}:${APP_PORT}"
    restart: unless-stopped
    depends_on:
      - db
  db:
    container_name: db
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: nest
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql

networks:
  default:
    external:
      name: app-network

volumes:
  mysql_data:
